apiVersion: v1
kind: Pod
metadata:
  name: todo-pod
  namespace: todo-app-namespace
spec:
  containers:
    - name: node-todo-container
      image: chitrakshipuri/node-app-test-new:latest
      ports:
        - containerPort: 6001

