apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app-namespace
spec:
  type: NodePort
  selector:
    app: node-todo-label
  ports:
    - port: 6001
      targetPort: 6001
      nodePort: 30002
