apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: sql-namespace
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/sqlvolumes"
